### ISSUE TITLE
Pick up synonyms file from elasticsearch host

### ISSUE THREAD

**Issue by wpears** [cfpb/grasshopper-loader#115]
A mapping needs to be applied to indices to pick up a synonyms file that maps, eg. rd -> road, st -> street, etc.

This will need to be done for EACH internal index, as applying a mapping to the alias itself (ie census) will cause a conflict when the internal index alias is applied (mapping it from internal index to alias will fail as an index of the name 'alias' will already exist).

**Comment by jmarin** [comment]
For current settings on TIGER data, see https://github.com/cfpb/grasshopper/blob/master/docs/tiger_data_spec.md#data-creation

**Comment by wpears** [comment]
Closed by #117
