### ISSUE TITLE
No STATE field present in TIGER schema

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper-loader#124]
The TIGER schema has lost the STATE field as described in https://github.com/cfpb/grasshopper/blob/master/docs/tiger_data_spec.md. This is needed for the Census search to work.

**Comment by wpears** [comment]
Ahh yes. I'll reimplement that post haste. On another note, all the address
data should be loaded on except DC
I'll do DC when I get home

**Comment by wpears** [comment]
Closed by #125
