### ISSUE TITLE
Investigate Kansas

### ISSUE THREAD

**Issue by kgudel** [cfpb/grasshopper-loader#185]
From #169 

There exists an [address data standard](http://data.kansasgis.org/dascweb/docs/files/2address.pdf) from 1999 which comes from the Kansas' Office of the Governor's, [Office of Information Technology Services](https://oits.ks.gov/kito/geographic-information/gis-home-page).

Further within the [Kansas Data Access and Support Center](http://www.kansasgis.org/docs/index.cfm?ob=1&StartRow=31). There is a [document](http://data.kansasgis.org/dascweb/docs/files/Kansas_NG911_GIS_Data_Model_v1.pdf) outlining a NG911 data model which includes address points, it was written by the GIS subcommittee on behalf of the [Kansas 911 Coordinating Council](http://www.kansas911.org/). 

There is a list of members [here](http://www.kansas911.org/107/911-Council-Members).

**Comment by kgudel** [comment]
We have received a file from Kansas and I will begin loading it.

@ericspry this is ready to add to the dig, however, as it stands it was a one time data extract so there isn't a sight to review, I can though give you whatever information that you need.

**Comment by ericspry** [comment]
Okay, thanks. Do we have any documentation from KS on terms of use, grant of license or anything that I can share with DIG to verify our right to use for the geocoder?
