### ISSUE TITLE
Load OpenAddress data

### ISSUE THREAD

**Issue by debseidner** [cfpb/grasshopper-loader#37]
As a geocoding system, I want the ability to pull data from OpenAddresses and automate the loading into ES so that so we can use and update this data automatically for locating the (x,y) for addresses

**Comment by wpears** [comment]
OpenAddresses doesn't seem to be a worthwhile source of data for the following reasons:
  - Incompleteness. Data is only lat/lon + street number and name per row. The source data almost certainly has more identifying information (zip, county, etc.). Sometimes some of this can be inferred from filenames; but quite often this isn't true. Without more identifying characteristics, a search for eg *100 Main St, Pawtucket RI 02904*, would actually return 9 equally-scored XYs.
  - Poor structure. A download/unzip of the entire US results in 408 .csvs over varying granularity, but with not enough specifics to engineer a simple solution. Example filenames: *us-ut.csv, us-wy-kenosha.csv, us-wa-city_of_spokane.csv, us-ny-nyc.csv, us-tx-austin.csv, us-vaz.csv, us-or-portland_metro.csv*.

The complexity of parsing the dataset's lack of structure into something meaningful that can inform the incompleteness of the fields is nontrivial even where it is possible. If we find ourselves lacking data that OpenAddresses contains, I may reopen this issue, but I think we'd be much better served using OpenAddresses as a *source of data sources* and get the raw, public data itself.
