### ISSUE TITLE
Automatic loading of state data 

### ISSUE THREAD

**Issue by debseidner** [cfpb/grasshopper-loader#38]
As a geocoding system, I want the ability to pull data from State databases (i.e. Arkansas, NY, MD, etc.)	so that it can be loaded into ES automatically and prepared for use in locating the (x,y) for addresses

**Comment by debseidner** [comment]
Linked to one-time load of state data - #9

**Comment by wpears** [comment]
This will be done in another repo: currently prototyping at https://github.com/wpears/retriever

Copying this issue there.
