### ISSUE TITLE
Download data

### ISSUE THREAD

**Issue by debseidner** [cfpb/grasshopper-loader#41]
As a geocoding system, I need to be able to download the data that I pulled from the various data sources so that I can get it ready for extraction and loading into the geocoding system

**Comment by wpears** [comment]
The loader now (as of https://github.com/cfpb/grasshopper-loader/pull/52) does this, and actually does one better by streaming the data directly to elasticsearch when possible, rather than downloading the whole dataset before extraction/loading.
